# Generated by Django 3.1 on 2020-09-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(max_length=256)),
                ('pincode', models.IntegerField()),
                ('officetype', models.CharField(max_length=256)),
                ('deliverystatus', models.CharField(max_length=256)),
                ('divisionname', models.CharField(max_length=256)),
                ('regionname', models.CharField(max_length=256)),
                ('circlename', models.CharField(max_length=256)),
                ('taluk', models.CharField(max_length=256)),
                ('districtname', models.CharField(max_length=256)),
                ('statename', models.CharField(max_length=256)),
                ('stateshort', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'india',
            },
        ),
    ]
